### jshint node:true ###

multiline = undefined
template = undefined
reportTemplate = undefined
reportFn = undefined
multiline = require('multiline')
template = require('string-interpolate')
reportTemplate = multiline(->

  ###
  { chalk.styles.yellow.open }{ nope } { path }:{ line } - { name } is too complicated{ chalk.styles.yellow.close }
      Cyclomatic: { complexity.cyclomatic }
      Halstead: { complexity.halstead.difficulty }
        | Effort: { complexity.halstead.effort }
        | Volume: { complexity.halstead.volume }
        | Vocabulary: { complexity.halstead.vocabulary }
  ###

  return
)
reportFn = template(reportTemplate)

exports.log = (file, report, options, fittedName) ->
  chalk = require('chalk')
  path = require('path')
  name = path.relative(file.cwd, file.path)
  helpers = require('./reporter-helpers')
  valid = true
  report.functions.filter((fn) ->
    cyclomatic = fn.cyclomatic
    halstead = fn.halstead
    cyclomatic > options.cyclomatic[0] or halstead.difficulty > options.halstead[0]
  ).map((fn) ->
    {
      path: name
      line: fn.line
      name: fn.name
      complexity: fn
      chalk: chalk
      nope: '✗'
    }
  ).forEach (report) ->
    valid = false
    console.log reportFn(report)
    return
  if valid
    console.log chalk.green('✓'), fittedName, helpers.generateBar(report.maintainability, options.maintainability)
  return

# ---
# generated by js2coffee 2.0.4
