do ->

  toRadians = (degrees) ->
    degrees * Math.PI / 180

  alignValue = (value) ->
    parseFloat value.toFixed(5)

  handleEvent = (event) ->
    type = event.type
    originalEvent = undefined
    originalEvent = if !touch.isTouch then event else event.changedTouches[0]
    switch type
      when touch.events.start
        if originalEvent.pageY > 450
          @element.addEventListener 'swipeleft', touch.stop
          @element.addEventListener 'swiperight', touch.stop
          @startX = originalEvent.pageX
        else
          @element.removeEventListener 'swipeleft', touch.stop
          @element.removeEventListener 'swiperight', touch.stop
      when touch.events.move
        if @startX
          @tempOffset = (@startX - (originalEvent.pageX)) * 0.2
          @update()
      when touch.events.end
        @startX = null
        @offset += @tempOffset
        @tempOffset = 0
    return

  Carousel = (element) ->
    @element = element
    @elements = element.children
    @stepAngle = 360 / @elements.length
    @radiusX = 330
    @radiusY = 190
    @radiusZ = 350
    @offset = 0
    @tempOffset = 0
    @startX = 0
    element.addEventListener touch.events.start, handleEvent.bind(this)
    element.addEventListener touch.events.move, handleEvent.bind(this)
    element.addEventListener touch.events.end, handleEvent.bind(this)
    @update()
    return

  'use strict'

  Carousel::update = ->
    radians = undefined
    i = undefined
    x = undefined
    y = undefined
    z = undefined
    opacity = undefined
    i = 0
    while i < @elements.length
      radians = toRadians(@stepAngle * i + @offset + 90 + @tempOffset)
      x = alignValue(@radiusX * Math.cos(radians))
      y = alignValue(@radiusY * Math.sin(radians)) - (@radiusY)
      z = alignValue(@radiusZ * Math.sin(radians)) - (@radiusZ)
      opacity = (z + @radiusZ) * 0.5 / 1300 + 0.75
      @elements[i].style.cssText = '-webkit-transform: translate3d(' + x + 'px, ' + y + 'px, ' + z + 'px); opacity: ' + opacity + ';'
      i++
    return

  window.Carousel = Carousel
  return

# ---
# generated by js2coffee 2.0.4
